### ISSUE TITLE
HttpError: Bad Credentials

### ISSUE THREAD

**Issue by miguel-ferradans** [pascalgn/automerge-action#187]
Hello, we've recently started using this action in a big project with a lot of engineers.

Very rarely the automerger action will fail to run due to this error:

```
2022-04-07T09:03:22.420Z INFO  Event name: pull_request
2022-04-07T09:03:22.421Z DEBUG Getting pull request info for 34807 ...
2022-04-07T09:03:22.513Z HttpError: Bad credentials
    at /home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:5138:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fetchPullRequest (/home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:440:[31](https://github.com/scopely/DiceUnity/runs/5865475287?check_suite_focus=true#step:2:31))
    at async handlePullRequestUpdate (/home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:128:23)
    at async executeGitHubActionImpl (/home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:105:12)
    at async executeGitHubAction (/home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:76:18)
    at async main (/home/runner/work/_actions/pascalgn/automerge-action/v0.15.2/dist/index.js:22215:5)
```
Any idea what is the cause of the issue?

**Comment by naz141** [comment]
Hi was this error "Bad credentials" resolved.
Im still having this problem in GHE
